# -*- coding: utf-8 -*-
"""main

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1L7TFF2vm-eHN2jbRbJGvo2B-PlS7gMJ3
"""

#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'diagonalDifference' function below.
#
# The function is expected to return an INTEGER.
# The function accepts 2D_INTEGER_ARRAY arr as parameter.
#

def diagonalDifference(arr):
    #arr =[[1,2,3],
    #  [4,5,6],
    #  [9,8,9]]

  res = arr[::-1]
  a = [ arr[i][i] for i in range(len(arr)) ]
  b = [ res[i][i] for i in range(len(res)) ]
  sa = 0
  sb = 0
  for i in a:
    sa += i
  for j in b:
    sb += j 

  result = abs(sa-sb)
  return result

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input().strip())

    arr = []

    for _ in range(n):
        arr.append(list(map(int, input().rstrip().split())))

    result = diagonalDifference(arr)

    fptr.write(str(result) + '\n')

    fptr.close()